import type { Metadata } from "next";
import { Exo } from "next/font/google";
import "./globals.css";
import NavBar from "./_Components/NavBar";
import Footer from "./_Components/Footer";
import TopBar from "@/app/_Components/TopBar";
import { Toaster } from "sonner";
import MySession from "./_Components/MySession/MySession";
import { ToastContainer } from 'react-toastify';
import 'react-toastify/dist/ReactToastify.css';
import ReduxProvider from "@/store/ReduxProvider";

const exoFont = Exo({
  subsets: ["latin"],
  variable: "--font-exo",
});

export const metadata: Metadata = {
  title: "Fresh cart",
  description: "Generated by ziad sayed",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={exoFont.variable}>
      <body className={`font-exo antialiased`}>
        <MySession>
          <ReduxProvider>
            <TopBar />
            <NavBar />
            <Toaster />
            <ToastContainer position="top-right" autoClose={3000} />
            {children}
            <Footer />
          </ReduxProvider>
        </MySession>
      </body>
    </html>
  );
}
